Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 62, in products
    return render(request, "pages/products.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pages/products.html
Internal Server Error: /product/b15faf33b3/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' if product.in_stock else "Out of Stock"' from '"In Stock" if product.in_stock else "Out of Stock"'
Internal Server Error: /product/3b2a4d3fhf/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
Internal Server Error: /product/3b2a4d3fhf/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
Internal Server Error: /product/3b2a4d3fhf/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
Internal Server Error: /product/3b2a4d3fhf/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
Internal Server Error: /product/3b2a4d3fhf/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 77, in product_detail
    return render(request, "pages/product/product_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/defaulttags.py", line 975, in do_if
    nodelist = parser.parse(("endif",))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 53: 'endblock', expected 'endif'. Did you forget to register or load this tag?
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 62, in products
    return render(request, "pages/product/products.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 1: 'block'. Looking for one of: endblock.
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 62, in products
    return render(request, "pages/product/products.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 1: 'block'. Looking for one of: endblock.
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 62, in products
    return render(request, "pages/product/products.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 1: 'block'. Looking for one of: endblock.
Internal Server Error: /contact/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 86, in contact
    return render(request, "pages/contact.html", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: website_pricelist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 16, in index
    return render(request, "pages/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/template/context.py", line 254, in bind_template
    context = processor(self.request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/context_processor.py", line 7, in default
    price_list = get_object_or_404(PriceList.objects.order_by("-date"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: website_pricelist
Internal Server Error: /
Internal Server Error: /favicon.ico
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/myprojects/django/heavy_champion_webapp/website/views.py", line 123, in products
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/jeco/.local/share/virtualenvs/heavy_champion_webapp-WbPUGAGY/lib/python3.11/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
